id: P002915
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W12829
  title: གསུང་ཐོར་བུ། དྲི་མེད་འོད་ཟེར།（ཨ་འཛོམ་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: ''
  volumes:
    8c53565368364b39a0413e62dacc3412:
      image_group_id: I00JW501147
      title: ''
      volume_number: 1
      total_pages: 624
      base_file: v001.txt
    0f43a94c93474dcfa087d931ff57c5e2:
      image_group_id: I00JW501148
      title: ''
      volume_number: 2
      total_pages: 634
      base_file: v002.txt
