id: IDFB347F4
legacy_id: P002915
ocr_import_info:
  bdrc_scan_id: W12829
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T20:53:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T13:27:31.368417+00:00'
last_modified: 2022-08-29 21:30:14.571479
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W12829
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW12829
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་ཐོར་བུ། དྲི་མེད་འོད་ཟེར།（ཨ་འཛོམ་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: ཀློང་ཆེན་རབ་འབྱམས་པ་དྲི་མེད་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.7944327428223555
  ocr_word_median_confidence_index: 0.8600000143051147
quality: null
bases:
  I00JW501147:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00JW501147
      total_pages: 624
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00JW501147.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7890151601088421
    legacy_id: v001
  I00JW501148:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00JW501148
      total_pages: 634
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00JW501148.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7998105375557412
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
