id: IDFB347F4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:57:21+00:00'
last_modified: '2022-06-07T16:09:59.818788+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W12829
  title: གསུང་ཐོར་བུ། དྲི་མེད་འོད་ཟེར།（ཨ་འཛོམ་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    35FF:
      image_group_id: I00JW501147
      title: ''
      total_pages: 624
      order: 1
      base_file: 35FF.txt
    E7AB:
      image_group_id: I00JW501148
      title: ''
      total_pages: 634
      order: 2
      base_file: E7AB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
